// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mrmr
Rcpp::List mrmr(Rcpp::NumericVector time, Rcpp::LogicalVector status, Rcpp::NumericMatrix x, int nselect);
RcppExport SEXP fmrmr_mrmr(SEXP timeSEXP, SEXP statusSEXP, SEXP xSEXP, SEXP nselectSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time(timeSEXP );
        Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type status(statusSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type nselect(nselectSEXP );
        Rcpp::List __result = mrmr(time, status, x, nselect);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
