// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cindex
arma::vec cindex(const arma::vec& time, const arma::uvec& status, const arma::mat& x);
RcppExport SEXP fmrmr_cindex(SEXP timeSEXP, SEXP statusSEXP, SEXP xSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP );
        Rcpp::traits::input_parameter< const arma::uvec& >::type status(statusSEXP );
        Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP );
        arma::vec __result = cindex(time, status, x);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// mrmr
Rcpp::List mrmr(const arma::vec& time, const arma::uvec& status, const arma::mat& x, size_t nselect);
RcppExport SEXP fmrmr_mrmr(SEXP timeSEXP, SEXP statusSEXP, SEXP xSEXP, SEXP nselectSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP );
        Rcpp::traits::input_parameter< const arma::uvec& >::type status(statusSEXP );
        Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP );
        Rcpp::traits::input_parameter< size_t >::type nselect(nselectSEXP );
        Rcpp::List __result = mrmr(time, status, x, nselect);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
