// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cindex
Rcpp::NumericVector cindex(const Rcpp::NumericVector& time, const Rcpp::LogicalVector& status, const Rcpp::NumericMatrix& x);
RcppExport SEXP fmrmr_cindex(SEXP timeSEXP, SEXP statusSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type status(statusSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cindex(time, status, x));
    return rcpp_result_gen;
END_RCPP
}
// mrmr_generic
Rcpp::List mrmr_generic(Rcpp::NumericVector relevance, Rcpp::NumericMatrix x, int nselect);
RcppExport SEXP fmrmr_mrmr_generic(SEXP relevanceSEXP, SEXP xSEXP, SEXP nselectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type relevance(relevanceSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nselect(nselectSEXP);
    rcpp_result_gen = Rcpp::wrap(mrmr_generic(relevance, x, nselect));
    return rcpp_result_gen;
END_RCPP
}
