# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cindex <- function(time, status, x) {
    .Call('fmrmr_cindex', PACKAGE = 'fmrmr', time, status, x)
}

mrmr <- function(time, status, x, nselect) {
    .Call('fmrmr_mrmr', PACKAGE = 'fmrmr', time, status, x, nselect)
}

