# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cindex <- function(time, status, x) {
    .Call('fmrmr_cindex', PACKAGE = 'fmrmr', time, status, x)
}

mrmr_generic <- function(relevance, x, nselect) {
    .Call('fmrmr_mrmr_generic', PACKAGE = 'fmrmr', relevance, x, nselect)
}

